name: "Master branch update"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --no-fund

  check:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
      - name: Upload build artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # use correct path

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
